config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [:index]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
  sessions: 'users/sessions',
  registrations: 'users/registrations' }
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
      member do
        patch :archive
      end
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one_attached :image
  has_many :likes, dependent: :destroy
  validates :content, length: { in: 1..100 }, allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @post = Post.find(params[:comment][:post_id])


    @comment.image.attach(params[:comment][:image])

    if @comment.save
      @notification = new_notification(@post.user, @post.id, 'comment')
      @notification.save
      redirect_to @post
    else
       redirect_to @post, alert: "Error creating comment."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    return unless current_user.id == @comment.user_id

    @comment.destroy
    flash[:success] = 'Comment deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% post.comments.each do |c| %>
  <div class="p-2">
    <div class="row mt-3">
      <div class="ml-2">
        <% if c.user.image_url %>
          <%= image_tag(c.user.image.url, class: "img-profile") %>
        <% end %>
      </div>
      <div class="mt-2">
        <div class="col font-weight-bold">
          <%= link_to user_path(c.user), class: "font-raleway" do %>
            <%= c.user.full_name %>
          <% end %>
        </div>
        <div class="col size-12">Posted <%= distance_of_time_in_words(c.created_at, Time.now) %> ago</div>
      </div>
    </div>

    <div class="row ml-5 pl-1">
      <div class="col-auto font-rale text-post">
        <%= c.content %>
        <% if current_user.id == c.user_id %>
          <%= link_to comment_path(c), method: :delete, data: { confirm: "You sure?" } do %>
            <i class="fas fa-trash hover-red"></i>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if c.image.attached? %>
      <div class="row ml-5 pl-1">
        <div class="col-auto">
          <%= image_tag c.image, class: "img-thumbnail comment-image" %>
        </div>
      </div>
    <% end %>

    <div class="row ml-5 pl-1">
      <div class="col-auto">
        <%= render 'likes/like_comments', object: c %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for comment, html: { multipart: true } do |f| %>
  <div class="error-messages">
    <% if comment.errors.any? %>
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= f.hidden_field :post_id, value: post.id %>

  <div class="form-group">
    <%= f.text_area :content, class: "comment-box", placeholder: "Type your comment..." %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Upload Image" %>
    <%= f.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit 'Comment', class: "btn bg-secondary m-0" %>
  </div>
<% end %>