config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [:index]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
  sessions: 'users/sessions',
  registrations: 'users/registrations' }
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
      member do
        patch :archive
      end
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :content, length: { in: 3..800 }, allow_blank: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy, :archive]

  def index
    @our_posts = current_user.friends_and_own_posts
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      create_notification_for_superadmin
      send_email_notification_to_superadmin(@post)
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    return unless current_user.id == @post.user_id

    @post.destroy
    flash[:success] = 'Post deleted'
    redirect_back(fallback_location: root_path)
  end

  def archive
    @post = Post.find(params[:id])

    if current_user.super_admin? || current_user == @post.user
      @post.update(archived: true)
      flash[:notice] = 'Post archived successfully.'
    else
      flash[:alert] = 'You do not have permission to archive this post.'
    end

    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def posts_params
    params.require(:post).permit(:content, :imageURL)
  end

  def create_notification_for_superadmin
    superadmin = User.with_role(:super_admin).first
    Notification.create(user: superadmin, content: "A new post was created.")
  end

  def send_email_notification_to_superadmin(post)
    superadmin = User.with_role(:super_admin).first
    SuperAdminMailer.new_post_notification(superadmin, post).deliver_now
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_layout.html.erb
<div class="col-md-7 mx-auto card-lg bg-light shadow">

  <div class="container">
    <div class="row mt-3">
      <div class="ml-2">
        <% if object.user.image_url %>
          <%= image_tag(object.user.image.url, class: "img-profile") %>
        <% end %>
      </div>
      <div class="mt-2">
        <div class="col font-weight-bold">
          <%= link_to user_path(object.user), class: "font-raleway" do %>
            <%= object.user.full_name %>
          <% end %>
        </div>
        <div class="col size-12">Posted <%= distance_of_time_in_words(object.created_at, Time.now) %> ago</div>
      </div>
    </div>
  </div>

  <div class="container-fluid mt-4 p-0">
    <% if object.imageURL.present? %>
      <div class="size-18 text-post">
        <%= object.content %>
      </div>
      <div class="center py-4">
        <%= image_tag(object.imageURL, class: "img-fill") %>
      </div>
    <% else %>
      <div class="size-18 text-post mb-2 ml-3">
        <%= object.content %>
      </div>
    <% end %>
    <% if current_user.id == object.user_id %>
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to post_path(object), method: :delete, data: { confirm: "You sure?" }, class: "hover-red" do %>
          <i class="fas fa-trash"></i>
        <% end %>
        <% if object.archived %>
          <span class="badge badge-secondary">Archived</span>
        <% else %>
          <%= link_to archive_post_path(object), method: :patch, class: "badge badge-warning" do %>
            Archive
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="border-bottom border-top">
    <div class="container">
      <%= render 'likes/like_posts', object: object %>
    </div>
  </div>

  <div class="pl-5 py-2">
    <div class="">
      <%= render 'comments/comment', post: object %>
    </div>
    <div class="col-10 mt-3">
      <%= render 'comments/form', comment: Comment.new, post: object %>
    </div>
  </div>
</div>
<br>

app/views/posts/archive.html.erb
<!-- app/views/posts/archive.html.erb -->
<div class="col-md-7 mx-auto card-lg bg-light shadow">
  <div class="container">
    <div class="row mt-3">
      <!-- Display Post Details and Archived Badge -->
    </div>
  </div>

  <div class="container-fluid mt-4 p-0">
    <!-- Display Post Content and Archived Badge -->
    <div class="d-flex justify-content-between align-items-center">
      <span class="badge badge-secondary">Archived</span>
    </div>
  </div>

  <!-- Likes and Comments Sections -->
</div>
<br>

app/views/posts/index.html.erb
<h1> Timeline - My posts and my friends posts</h1>
<div class="center font-raleway ">
  <%= link_to new_post_path, class: "btn btn-secondary" do%>
    New Post?
  <%end%>
</div>
<% @our_posts.each do |p|%>
  <%= render 'posts/post_layout', object: p %>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-6 mx-auto">
  <h1 class="center bold">Whats on your mind?</h1>
  <p>Create a new post for your friends to spy on</p>

  <%= form_for(@post) do |f| %>
      <%= render "devise/shared/error_messages", resource: @post %>
      <div class="form-group">
        <%= f.text_area :content, class:"form-control" %><br />
      </div>
      <div class="form-group">
        Image by URL: 
        <p>Allow an image in your post by entering a link to the image</p>
        <%= f.text_field :imageURL, class:"form-control" %>
        <br />
      </div>
      <div>
        <%= f.submit 'New Post', class:"btn btn-secondary col-md-3"%>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Post</h1>

<%= render 'posts/post_layout', object: @post %>